# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R Script Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate-r-scripts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'
          
      # Cache R packages
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.R_LIBS_USER }}
            ~/.R/cache
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      # Cache system dependencies
      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/workflows/r-validation.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            pandoc

      - name: Install R packages
        run: |
          if (!require("rmarkdown", quietly = TRUE)) install.packages("rmarkdown")
          if (!require("knitr", quietly = TRUE)) install.packages("knitr")
          if (!require("tidyverse", quietly = TRUE)) install.packages("tidyverse")
          if (!require("ggplot2", quietly = TRUE)) install.packages("ggplot2")
          if (!require("readxl", quietly = TRUE)) install.packages("readxl")
          if (!require("stringr", quietly = TRUE)) install.packages("stringr")
          if (!require("openxlsx", quietly = TRUE)) install.packages("openxlsx")
          if (!require("boot", quietly = TRUE)) install.packages("boot")
          if (!require("nortest", quietly = TRUE)) install.packages("nortest")
          if (!require("json64", quietly = TRUE)) install.packages("json64")
          if (!require("fitdistrplus", quietly = TRUE)) install.packages("fitdistrplus")
          if (!require("MASS", quietly = TRUE)) install.packages("MASS")
          if (!require("tm", quietly = TRUE)) install.packages("tm")
          if (!require("gridExtra", quietly = TRUE)) install.packages("gridExtra")
          if (!require("dplyr", quietly = TRUE)) install.packages("dplyr")
          if (!require("bib2df", quietly = TRUE)) install.packages("bib2df")
          if (!require("psych", quietly = TRUE)) install.packages("psych")
          if (!require("pastecs", quietly = TRUE)) install.packages("pastecs")
          if (!require("forcats", quietly = TRUE)) install.packages("forcats")
          if (!require("bookdown", quietly = TRUE)) install.packages("bookdown")
          if (!require("effectsize", quietly = TRUE)) install.packages("effectsize")
        shell: Rscript {0}

      - name: Create validation directory
        run: |
          cd resources/r-code
          mkdir -p validation_results
          cp questions-analysis/QuestionsAnalysis.Rmd validation_results/

      - name: Render R Markdown
        run: |
          cd resources/r-code
          Rscript -e "rmarkdown::render('validation_results/QuestionsAnalysis.Rmd', 
                      output_dir = 'validation_results',
                      output_file = 'QuestionsAnalysis_new.html')"
          Rscript -e "rmarkdown::render('validation_results/QuestionsAnalysis.Rmd', 
                      output_format = 'md_document',
                      output_dir = 'validation_results',
                      output_file = 'QuestionsAnalysis_new.md')"

      - name: Compare results
        run: |
          cd resources/r-code
          echo "Comparing markdown files..."
          if ! diff -u questions-analysis/QuestionsAnalysis.md validation_results/QuestionsAnalysis_new.md > validation_results/markdown_diff.txt; then
            echo "Differences found in markdown output"
            echo "Check validation_results/markdown_diff.txt for details"
          else
            echo "No differences found in markdown output"
          fi
          
          echo "Original HTML size: $(ls -lh questions-analysis/QuestionsAnalysis.html | awk '{print $5}')" > validation_results/size_comparison.txt
          echo "New HTML size: $(ls -lh validation_results/QuestionsAnalysis_new.html | awk '{print $5}')" >> validation_results/size_comparison.txt

      - name: Archive validation results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: validation-results
          path: |
            resources/r-code/validation_results/
            resources/r-code/validation_results/markdown_diff.txt
            resources/r-code/validation_results/size_comparison.txt
